name    'sbadia-bird'
version '0.0.3'
source  'https://github.com/sbadia/puppet-bird'
author  'Sebastien Badia'
license 'GPLv3'
summary 'Puppet bird Module'
description 'Module to install/manage Bird internet routing daemon using puppet'
project_page 'https://github.com/sbadia/puppet-bird/'
